spring:
  application:
    name: demo

server:
  servlet:
    context-path: /demo

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
