app:
  name: ${APP_NAME:demo}

demo:
  target-one-host: ${TARGET_ONE_HOST:app-b}
  target-two-host: ${TARGET_TWO_HOST:app-c}

spring:
  application:
    name: demo

server:
  servlet:
    context-path: /demo

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
