apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-demo
  labels:
    app: opentelemetry-demo
spec:
  type: NodePort
  selector:
    app: opentelemetry-demo
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
